// Code generated by mockery. DO NOT EDIT.

package test_utils

import (
	mock "github.com/stretchr/testify/mock"

	summarizer "processing-orchestrator/pkg/summarizer"
)

// MockSummarizingService is an autogenerated mock type for the SummarizingService type
type MockSummarizingService struct {
	mock.Mock
}

type MockSummarizingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSummarizingService) EXPECT() *MockSummarizingService_Expecter {
	return &MockSummarizingService_Expecter{mock: &_m.Mock}
}

// Submit provides a mock function with given fields: req
func (_m *MockSummarizingService) Submit(req *summarizer.SummaryJob) error {
	ret := _m.Called(req)

	var r0 error
	if rf, ok := ret.Get(0).(func(*summarizer.SummaryJob) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSummarizingService_Submit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Submit'
type MockSummarizingService_Submit_Call struct {
	*mock.Call
}

// Submit is a helper method to define mock.On call
//   - req *summarizer.SummaryJob
func (_e *MockSummarizingService_Expecter) Submit(req interface{}) *MockSummarizingService_Submit_Call {
	return &MockSummarizingService_Submit_Call{Call: _e.mock.On("Submit", req)}
}

func (_c *MockSummarizingService_Submit_Call) Run(run func(req *summarizer.SummaryJob)) *MockSummarizingService_Submit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*summarizer.SummaryJob))
	})
	return _c
}

func (_c *MockSummarizingService_Submit_Call) Return(_a0 error) *MockSummarizingService_Submit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSummarizingService_Submit_Call) RunAndReturn(run func(*summarizer.SummaryJob) error) *MockSummarizingService_Submit_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSummarizingService creates a new instance of MockSummarizingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSummarizingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSummarizingService {
	mock := &MockSummarizingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
