// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.2
// source: pkg/thumb-generator/proto/thumbnail.proto

package thumbnail_generator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ThumbnailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GmsAvatarUrl  []string `protobuf:"bytes,1,rep,name=gmsAvatarUrl,proto3" json:"gmsAvatarUrl,omitempty"`
	Title         string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	EpisodeTitle  string   `protobuf:"bytes,3,opt,name=episodeTitle,proto3" json:"episodeTitle,omitempty"`
	EpisodeIndex  int32    `protobuf:"varint,4,opt,name=episodeIndex,proto3" json:"episodeIndex,omitempty"`
	BackgroundUrl string   `protobuf:"bytes,5,opt,name=backgroundUrl,proto3" json:"backgroundUrl,omitempty"`
	LogoUrl       string   `protobuf:"bytes,6,opt,name=logoUrl,proto3" json:"logoUrl,omitempty"`
}

func (x *ThumbnailRequest) Reset() {
	*x = ThumbnailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_thumb_generator_proto_thumbnail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThumbnailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailRequest) ProtoMessage() {}

func (x *ThumbnailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_thumb_generator_proto_thumbnail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailRequest.ProtoReflect.Descriptor instead.
func (*ThumbnailRequest) Descriptor() ([]byte, []int) {
	return file_pkg_thumb_generator_proto_thumbnail_proto_rawDescGZIP(), []int{0}
}

func (x *ThumbnailRequest) GetGmsAvatarUrl() []string {
	if x != nil {
		return x.GmsAvatarUrl
	}
	return nil
}

func (x *ThumbnailRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ThumbnailRequest) GetEpisodeTitle() string {
	if x != nil {
		return x.EpisodeTitle
	}
	return ""
}

func (x *ThumbnailRequest) GetEpisodeIndex() int32 {
	if x != nil {
		return x.EpisodeIndex
	}
	return 0
}

func (x *ThumbnailRequest) GetBackgroundUrl() string {
	if x != nil {
		return x.BackgroundUrl
	}
	return ""
}

func (x *ThumbnailRequest) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

type ThumbnailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThumbnailKey string `protobuf:"bytes,1,opt,name=thumbnailKey,proto3" json:"thumbnailKey,omitempty"`
}

func (x *ThumbnailResponse) Reset() {
	*x = ThumbnailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_thumb_generator_proto_thumbnail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThumbnailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailResponse) ProtoMessage() {}

func (x *ThumbnailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_thumb_generator_proto_thumbnail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailResponse.ProtoReflect.Descriptor instead.
func (*ThumbnailResponse) Descriptor() ([]byte, []int) {
	return file_pkg_thumb_generator_proto_thumbnail_proto_rawDescGZIP(), []int{1}
}

func (x *ThumbnailResponse) GetThumbnailKey() string {
	if x != nil {
		return x.ThumbnailKey
	}
	return ""
}

var File_pkg_thumb_generator_proto_thumbnail_proto protoreflect.FileDescriptor

var file_pkg_thumb_generator_proto_thumbnail_proto_rawDesc = []byte{
	0x0a, 0x29, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x2d, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x68, 0x75, 0x6d,
	0x62, 0x6e, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x74, 0x68, 0x75,
	0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x22, 0xd4, 0x01, 0x0a, 0x10, 0x54, 0x68, 0x75, 0x6d, 0x62,
	0x6e, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x67,
	0x6d, 0x73, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0c, 0x67, 0x6d, 0x73, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x70, 0x69, 0x73, 0x6f, 0x64, 0x65,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x70, 0x69,
	0x73, 0x6f, 0x64, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x70, 0x69,
	0x73, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x65, 0x70, 0x69, 0x73, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x24, 0x0a,
	0x0d, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x55, 0x72, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x55, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x67, 0x6f, 0x55, 0x72, 0x6c, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x6f, 0x55, 0x72, 0x6c, 0x22, 0x37, 0x0a,
	0x11, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x4b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e,
	0x61, 0x69, 0x6c, 0x4b, 0x65, 0x79, 0x32, 0x5b, 0x0a, 0x09, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e,
	0x61, 0x69, 0x6c, 0x12, 0x4e, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x68, 0x75,
	0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x12, 0x1b, 0x2e, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61,
	0x69, 0x6c, 0x2e, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x2e,
	0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x17, 0x5a, 0x15, 0x2e, 0x2f, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61,
	0x69, 0x6c, 0x2d, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_thumb_generator_proto_thumbnail_proto_rawDescOnce sync.Once
	file_pkg_thumb_generator_proto_thumbnail_proto_rawDescData = file_pkg_thumb_generator_proto_thumbnail_proto_rawDesc
)

func file_pkg_thumb_generator_proto_thumbnail_proto_rawDescGZIP() []byte {
	file_pkg_thumb_generator_proto_thumbnail_proto_rawDescOnce.Do(func() {
		file_pkg_thumb_generator_proto_thumbnail_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_thumb_generator_proto_thumbnail_proto_rawDescData)
	})
	return file_pkg_thumb_generator_proto_thumbnail_proto_rawDescData
}

var file_pkg_thumb_generator_proto_thumbnail_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_thumb_generator_proto_thumbnail_proto_goTypes = []interface{}{
	(*ThumbnailRequest)(nil),  // 0: thumbnail.ThumbnailRequest
	(*ThumbnailResponse)(nil), // 1: thumbnail.ThumbnailResponse
}
var file_pkg_thumb_generator_proto_thumbnail_proto_depIdxs = []int32{
	0, // 0: thumbnail.Thumbnail.CreateThumbnail:input_type -> thumbnail.ThumbnailRequest
	1, // 1: thumbnail.Thumbnail.CreateThumbnail:output_type -> thumbnail.ThumbnailResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_thumb_generator_proto_thumbnail_proto_init() }
func file_pkg_thumb_generator_proto_thumbnail_proto_init() {
	if File_pkg_thumb_generator_proto_thumbnail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_thumb_generator_proto_thumbnail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThumbnailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_thumb_generator_proto_thumbnail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThumbnailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_thumb_generator_proto_thumbnail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_thumb_generator_proto_thumbnail_proto_goTypes,
		DependencyIndexes: file_pkg_thumb_generator_proto_thumbnail_proto_depIdxs,
		MessageInfos:      file_pkg_thumb_generator_proto_thumbnail_proto_msgTypes,
	}.Build()
	File_pkg_thumb_generator_proto_thumbnail_proto = out.File
	file_pkg_thumb_generator_proto_thumbnail_proto_rawDesc = nil
	file_pkg_thumb_generator_proto_thumbnail_proto_goTypes = nil
	file_pkg_thumb_generator_proto_thumbnail_proto_depIdxs = nil
}
